### ISSUE TITLE
cacheを使う

### ISSUE THREAD

**Issue by shippokun** [uchikun2493/actions_test#1]
# 概要
github actionsにはcacheがあって、それを利用すると同じパッケージバージョンなら初回以降の実行時間が短くなります

# 参考サイト
https://github.com/actions/cache/blob/master/examples.md#python---pip

**Comment by uchikun2493** [comment]
:vimlogo: 使いは:god: が多くて:emoi: から:parrot_fast: ！！！

**Comment by uchikun2493** [comment]
学んだ
後は良い感じに改良するのでcloseします
